"""Prometheus metrics: definitions, the HTTP middleware, and the renderer.

Domain counters are incremented at the point of truth in the services (ingestion,
detection, response, drift) and in the WebSocket manager; HTTP request/latency is
recorded by :class:`MetricsMiddleware`. Labels are deliberately low-cardinality
and never carry sensitive values (no usernames, IPs, IDs, tokens) — only method,
matched route template, status, and small enums.
"""

from __future__ import annotations

import time

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.requests import Request
from starlette.responses import Response

# ---------------------------------------------------------------------------
# Metric definitions.
# ---------------------------------------------------------------------------

HTTP_REQUESTS = Counter(
    "sentinelai_http_requests_total",
    "HTTP requests by method, matched route, and status code.",
    ["method", "route", "status"],
)
HTTP_LATENCY = Histogram(
    "sentinelai_http_request_duration_seconds",
    "HTTP request latency in seconds by method and matched route.",
    ["method", "route"],
)

WS_CONNECTIONS = Gauge(
    "sentinelai_websocket_active_connections",
    "Currently connected dashboard WebSocket clients.",
)

INGESTION_JOBS = Counter(
    "sentinelai_ingestion_jobs_total",
    "Ingestion jobs by terminal status.",
    ["status"],  # completed | failed
)
INGESTION_ROWS = Counter(
    "sentinelai_ingestion_rows_total",
    "Ingested flow rows by outcome.",
    ["outcome"],  # valid | invalid
)

DETECTION_RUNS = Counter("sentinelai_detection_runs_total", "Detection runs executed.")
DETECTION_EVENTS = Counter(
    "sentinelai_detection_events_total", "Events classified by the detector."
)
DETECTION_ALERTS = Counter("sentinelai_detection_alerts_total", "Alerts created by the detector.")

RESPONSE_ACTIONS = Counter(
    "sentinelai_response_actions_total",
    "Response actions by status transition and action type.",
    ["status", "type"],  # executed | pending | rejected ; action_type
)

REPORTS = Counter(
    "sentinelai_reports_total",
    "Incident reports generated by kind.",
    ["kind"],  # PER_ALERT | DAILY_SUMMARY
)

DRIFT_SCORE = Gauge(
    "sentinelai_drift_score",
    "Most recent model drift score (0 = stable).",
)
DRIFT_RUNS = Counter(
    "sentinelai_drift_runs_total",
    "Drift checks that produced a snapshot, by status bucket.",
    ["status"],  # OK | WATCH | DRIFT
)


# ---------------------------------------------------------------------------
# Render.
# ---------------------------------------------------------------------------


def render_latest() -> tuple[bytes, str]:
    """Return ``(body, content_type)`` for the /metrics exposition response."""
    return generate_latest(), CONTENT_TYPE_LATEST


# ---------------------------------------------------------------------------
# HTTP middleware.
# ---------------------------------------------------------------------------


def _route_template(request: Request) -> str:
    """The matched route's path template (low cardinality), or 'unmatched'.

    Using the template (e.g. ``/api/v1/alerts/{alert_id}``) instead of the raw
    path keeps label cardinality bounded and avoids leaking IDs. Unmatched paths
    (404s, scanners) collapse to a single ``unmatched`` series.
    """
    route = request.scope.get("route")
    path = getattr(route, "path", None)
    return path or "unmatched"


class MetricsMiddleware(BaseHTTPMiddleware):
    """Records request count + latency per method/route/status. Innermost so the
    route template is resolved (routing runs in ``call_next``)."""

    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        start = time.perf_counter()
        response = await call_next(request)
        elapsed = time.perf_counter() - start
        route = _route_template(request)
        HTTP_REQUESTS.labels(request.method, route, str(response.status_code)).inc()
        HTTP_LATENCY.labels(request.method, route).observe(elapsed)
        return response
